### ISSUE TITLE
I can not see web preview

### ISSUE THREAD

**Issue by cihiri39180** [expo/snack-web#55]
### when I clone the repo and start it the web preview does not show.

**Terminal Output**
```
λ ~/Desktop/Tests/snack-web/ master* yarn start                                   
yarn run v1.21.1
$ if-env NODE_ENV=production && yarn start:prod || yarn start:dev
$ yarn domain
$ hotel start && hotel add http://localhost:3011 --name snack.expo
Started http://localhost:2000
Create ~/.hotel/servers/snack.expo.json
$ nodemon -e json,js,ts,tsx --watch src/server src/server/index.tsx --exec babel-node --extensions '.ts,.tsx'
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/server/**/*
[nodemon] watching extensions: json,js,ts,tsx
[nodemon] starting `babel-node src/server/index.tsx --extensions .ts,.tsx`
The Snack web server is listening on http://:::3011

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3



  Error: The "SNACK_APP_URL" environment variable must be defined to proxy the Web player.
      at /home/prasanta/Desktop/Tests/snack-web/src/server/routes.tsx:145:13
      at dispatch (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-compose/index.js:42:32)
      at /home/prasanta/Desktop/Tests/snack-web/node_modules/koa-compose/index.js:34:12
      at dispatch (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-compose/index.js:42:32)
      at bodyParser (/home/prasanta/Desktop/Tests/snack-web/node_modules/koa-bodyparser/index.js:95:11)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at /home/prasanta/Desktop/Tests/snack-web/src/server/index.tsx:63:5
      at /home/prasanta/Desktop/Tests/snack-web/src/server/sw.tsx:18:5


ℹ ｢wdm｣: wait until bundle finished: /dist/assets/bc351fd24f9bd32bc131f122d42c1a77.svg
ℹ ｢wdm｣: wait until bundle finished: /dist/assets/8d8826a0f65854e909f64c244e1230b9.svg
ℹ ｢wdm｣: wait until bundle finished: /dist/assets/d14a681a76bdb229e305aa965b54dd18.png
ℹ ｢wdm｣: wait until bundle finished: /dist/assets/d93a5d445d7b7a8be13f38362a9dcf7e.png
ℹ ｢wdm｣: wait until bundle finished: /dist/assets/9682e34e1f058feab75a232e3b9f33c6.png
ℹ ｢wdm｣: wait until bundle finished: /dist/assets/c51d82a43adccd86d66477bfc28dd39b.png
```
*Browser Preview*
![Screenshot from 2020-11-24 15-05-17](https://user-images.githubusercontent.com/61316345/100075860-805c3300-2e66-11eb-8a2e-bd3be1f01e8a.png)

**Comment by cihiri39180** [comment]
I Saw this

> [https://github.com/expo/snack-web#testing-the-web-player-locally](url)

By default, the web player is loaded from s3. When developing locally, we can specify the SNACK_APP_URL environment variable to use our local instance of the web player instead.

Example:

`SNACK_APP_URL=http://192.168.1.3:19006 API_SERVER_URL=https://staging.snack.expo.io IMPORT_SERVER_URL=https://staging.snackager.expo.io yarn start`

### but form where I can run web player server offline? 
which points to SNACK_APP_URL

**Comment by IjzerenHein** [comment]
Hi! I'm sorry this repository has not been maintained for some time. We have just moved the Snack web app to the new Snack monorepo at https://github.com/expo/snack

You can find instructions there on how to run the website.

> but form where I can run web player server offline?

It is not possible for external contributors to do that at the moment.


The `expo/snack-web` repo will be archived, please report any issues in the new https://github.com/expo/snack repository.
